using System.Collections;
using System.Collections.Generic;
using UnityEngine.UI;
using UnityEngine;

public class controlgeneral : MonoBehaviour
{
    
    public GameObject b1;
    public GameObject b2;
    public GameObject b3;
    public GameObject b4;
    public GameObject b5;
    public GameObject b6;
    public GameObject b7;
    public GameObject b8;
    public GameObject b9;
    public GameObject b10;
    public GameObject b11;
    public GameObject b12;
    public GameObject b13;
    public GameObject b14;
    public GameObject b15;
    public GameObject b16;
    public GameObject b17;
    public GameObject b18;
    public GameObject h1;
    public GameObject h2;
    public GameObject h3;
    public GameObject h4;
    public GameObject h5;
    public GameObject h6;
    public GameObject h7;
    public GameObject h8;
    public GameObject h9;
    public GameObject h10;
    public GameObject h11;
    public GameObject h12;
    public GameObject h13;
    public GameObject h14;
    public GameObject h15;
    public GameObject h16;
    public GameObject h17;
    public GameObject h18;
    public GameObject back;
    public GameObject adelante;
    public GameObject atras;
    public GameObject adelante1;
    public GameObject atras1;



    // Start is called before the first frame update
    void Start()
    {
        // anuncioador.instance.RequestBanner();
        h1.SetActive(false);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(true);
        b2.SetActive(true);
        b3.SetActive(true);
        b4.SetActive(true);
        b5.SetActive(true);
        b6.SetActive(true);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(true);
        adelante.SetActive(true);
        atras1.SetActive(false);
        adelante1.SetActive(false);
        back.SetActive(false);
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    public void regreso()
    {
        h1.SetActive(false);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(true);
        b2.SetActive(true);
        b3.SetActive(true);
        b4.SetActive(true);
        b5.SetActive(true);
        b6.SetActive(true);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(true);
        adelante.SetActive(true);
        atras1.SetActive(false);
        adelante1.SetActive(false);
        back.SetActive(false);

    }

    public void mas()
    {
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(true);
        b8.SetActive(true);
        b9.SetActive(true);
        b10.SetActive(true);
        b11.SetActive(true);
        b12.SetActive(true);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(true);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(true);


    }
    public void mas1()
    {
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(true);
        b14.SetActive(true);
        b15.SetActive(true);
        b16.SetActive(true);
        b17.SetActive(true);
        b18.SetActive(true);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(true);
        adelante1.SetActive(true);


    }

    public void menos()
    {
        b1.SetActive(true);
        b2.SetActive(true);
        b3.SetActive(true);
        b4.SetActive(true);
        b5.SetActive(true);
        b6.SetActive(true);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(true);
        adelante.SetActive(true);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }
    public void menos1()
    {
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(true);
        b8.SetActive(true);
        b9.SetActive(true);
        b10.SetActive(true);
        b11.SetActive(true);
        b12.SetActive(true);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(true);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(true);
    }

    public void hech1()
    {
        h1.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);

    }
    public void hech2()
    {
        h2.SetActive(true);
        back.SetActive(true);
        h1.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }
    public void hech3()
    {
        h3.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h1.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }
    public void hech4()
    {
        h4.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h1.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }
    public void hech5()
    {
        h5.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h1.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }

    public void hech6()
    {
        h6.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h1.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }

    public void hech7()
    {
        h7.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h1.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }

    public void hech8()
    {
        h8.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h1.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }

    public void hech9()
    {
        h9.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h1.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }
    public void hech10()
    {
        h10.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h1.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }
    public void hech11()
    {
        h11.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h1.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }

    public void hech12()
    {
        h12.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h1.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }

    public void hech13()
    {
        h13.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h1.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }

    public void hech14()
    {
        h14.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h1.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }
    public void hech15()
    {
        h15.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h1.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }
    public void hech16()
    {
        h16.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h1.SetActive(false);
        h17.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }
    public void hech17()
    {
        h17.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h1.SetActive(false);
        h18.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }
    public void hech18()
    {
        h18.SetActive(true);
        back.SetActive(true);
        h2.SetActive(false);
        h3.SetActive(false);
        h4.SetActive(false);
        h5.SetActive(false);
        h6.SetActive(false);
        h7.SetActive(false);
        h8.SetActive(false);
        h9.SetActive(false);
        h10.SetActive(false);
        h11.SetActive(false);
        h12.SetActive(false);
        h13.SetActive(false);
        h14.SetActive(false);
        h15.SetActive(false);
        h16.SetActive(false);
        h17.SetActive(false);
        h1.SetActive(false);
        b1.SetActive(false);
        b2.SetActive(false);
        b3.SetActive(false);
        b4.SetActive(false);
        b5.SetActive(false);
        b6.SetActive(false);
        b7.SetActive(false);
        b8.SetActive(false);
        b9.SetActive(false);
        b10.SetActive(false);
        b11.SetActive(false);
        b12.SetActive(false);
        b13.SetActive(false);
        b14.SetActive(false);
        b15.SetActive(false);
        b16.SetActive(false);
        b17.SetActive(false);
        b18.SetActive(false);
        atras.SetActive(false);
        adelante.SetActive(false);
        atras1.SetActive(false);
        adelante1.SetActive(false);
    }
}
 